version: '3.8'

services:
  postgres-server:
    platform: linux/amd64
    image: postgres:14.0
    container_name: postgres-server
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "myuser", "-d", "mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.postgres.db
    networks:
      - mlops-postgres-network

  data-generator:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile_iris
    container_name: data-generator
    depends_on:
      postgres-server:
        condition: service_healthy
    command: ["postgres-server"]
    networks:
      - mlops-postgres-network

networks:
  mlops-postgres-network:
    external: true